name: Playwright Tests

permissions:
  contents: write
  pages: write
  id-token: write

on:
  workflow_dispatch:
    inputs:
      batch_name:
        description: "Batch Name"
        required: false
        default: ""

jobs:
  test:
    timeout-minutes: 240
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
        shardTotal: [12]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Install deps
        run: npm ci
      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run default
        if: github.event.inputs.batch_name == '' || github.event.inputs.batch_name == null
        run: npx playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }} --reporter=blob

      - name: Run batch
        if: github.event.inputs.batch_name != '' && github.event.inputs.batch_name != null
        env:
          BATCH: ${{ github.event.inputs.batch_name }}
        run: npx playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }} --reporter=blob

      - name: Upload Blob
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: blob-report-${{ matrix.shardIndex }}
          path: blob-report
          retention-days: 1

  merge-reports:
    if: always()
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: npm ci
      - name: Download blobs
        uses: actions/download-artifact@v4
        with:
          path: all-blob-reports
          pattern: blob-report-*
          merge-multiple: true
      - name: Merge into Allure Results
        run: |
          mkdir -p ./all-blob-reports
          npx playwright merge-reports --reporter allure-playwright ./all-blob-reports
      - name: Generate Allure Report
        run: npx allure generate allure-results -o allure-report --clean
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-html-report
          path: allure-report
          retention-days: 14
      - name: Prepare lightweight report for GitHub Pages
        if: always()
        run: |
          cp -r allure-report allure-pages
          find allure-pages -name "*.webm" -type f -delete
          find allure-pages -name "*.zip" -type f -delete
      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-pages
          publish_branch: gh-pages
          destination_dir: ${{ github.run_number }}
